#ifndef _PLANE_GEOMETRY_ATTRIBUTE_GLSL_
#define _PLANE_GEOMETRY_ATTRIBUTE_GLSL_

#define PLANE_ATTRIBUTE_POSITION(LOC, NAME) layout(location = LOC) in vec3 NAME
#define PLANE_ATTRIBUTE_UV(LOC, NAME) layout(location = LOC) in vec2 NAME

#endif//_PLANE_GEOMETRY_ATTRIBUTE_GLSL_